
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://thphmzmkltuvqkvoclwz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRocGhtem1rbHR1dnFrdm9jbHd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxOTkxNzQsImV4cCI6MjA1ODc3NTE3NH0.8bv3NUxoUX8OBNg5yyiZ97SOKPs2ChDt7rv3r0suT0w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
